### PR TITLE
Fix P-NP

### PR DESCRIPTION
**Pull request by Erisfiregamer1**
Now works by default (on repl.it anyway)

### CODE REVIEW

**Comment by donaldli2020** [comment]
[pmgh.zip](https://github.com/ProdigyPNP/P-NP/files/8457138/pmgh.zip)

**Comment by Erisfiregamer1** [comment]
I'm sure DeepScan means nothing.
(testing on self, if works then pog)

**Comment by donaldli2020** [comment]
dist/index.js:72:7
unexpected token \

**Comment by donaldli2020** [comment]
lol

**Comment by Erisfiregamer1** [comment]
Thoughts before I merge? (Might try to add /src back later instead of forcing maintainers to manually edit the dist)

**Comment by afkvido** [comment]
Alright, so DeepScan is just worrying about unused imports and variables, we can ignore that safely.

**Comment by afkvido** [comment]
> Thoughts before I merge? (Might try to add /src back later instead of forcing maintainers to manually edit the dist)

Try to fix the build if you can, that would help.
Like, make the dist update when we `npm build`

**Comment by afkvido** [comment]
Also, @Erisfiregamer1, before i (or anyone else) buy a VPS, we should run it on repl.it, and use uptimerobot to ping it

**Comment by Erisfiregamer1** [comment]
> Also, @Erisfiregamer1, before i (or anyone else) buy a VPS, we should run it on repl.it, and use uptimerobot to ping it

Already done. Also, I'm using Oracle Cloud since they offer a godly free VPS.

**Comment by donaldli2020** [comment]
is it a free trial or something

**Comment by Erisfiregamer1** [comment]
> > Thoughts before I merge? (Might try to add /src back later instead of forcing maintainers to manually edit the dist)
> 
> Try to fix the build if you can, that would help. Like, make the dist update when we `npm build`

Will do ASAP. For now, though, just edit the dist if you want to modify P-NP.
I'll fix the build later.

**Comment by donaldli2020** [comment]
@afkvido Weird thing: I don't have write access.

**Review by afkvido — COMMENTED** [review]
Keep

**Review by afkvido — COMMENTED** [review]
Keep

**Review by afkvido — COMMENTED** [review]
Keep

**Review by afkvido — COMMENTED** [review]
## PLEASE SEE BELOW:
Change Line 15 to:

``` js
   || "https://raw.githubusercontent.com/ProdigyPNP/ProdigyMathGameHacking/master/willsCheatMenu/dist/bundle.js";
```

**Review by afkvido — COMMENTED** [review]
Keep

**Review by afkvido — COMMENTED** [review]
Keep

###### hell yeah :)

**Review by afkvido — COMMENTED** [review]
Revert because we need to bring back /src

**Review by afkvido — COMMENTED** [review]
Keep

**Review by afkvido — COMMENTED** [review]
Keep, if this works

**Review by afkvido — COMMENTED** [review]
# revert

we need to modify the src, find a way to build (like `npx tsc`, `npx webpack`, `npm build`, or whatever the command is)

modifying the dist makes the code
1. VERY UNSTABLE
2. Versioning is incredibly difficult, think `package.json` kinda stuff

**Review by afkvido — COMMENTED** [review]
We need to find the proper build command then re-add it

**Comment by afkvido** [comment]
@Erisfiregamer1 Alr...


## Please change some stuff.

1. Make the cheat bundle link to`ProdigyPNP/ProdigyMathGameHacking`, that's the main one that we collab on
2. Comment out analytics, don't remove it. 
3. Keep /src, and make all your changes IN SRC.
4. Updating the dist manually means you've made an obscure alternate timeline. Please make all the changes in /src, THEN use node package manager to build the dist. (not manually edtiting the dist)
5. Anyway, CHEERS ON MAKING A WORKING INSTANCE OF P-NP! HIP HIP HORRRAYYYYYYYYY

**Comment by Erisfiregamer1** [comment]
1. Will do.
2. Aight.
3. Making changes in /src just... didn't work. It broke so much stuff that me and Donaldi removed it.
4. See 3.
5. You're welcome!

**Comment by Erisfiregamer1** [comment]
> We need to find the proper build command then re-add it

Proper build command is ```npx tsc```

**Comment by afkvido** [comment]
Perfect, thank you

**Pull request merged**
