### PR TITLE
Fix Problems

### PR DESCRIPTION
**Pull request by hostedposted**
Fixes the hack

### CODE REVIEW

**Comment by afkvido** [comment]
Hostedposted, please DM me the code of obfuscatedCode.js on Discord.

**Comment by afkvido** [comment]
@hostedposted I'll merge just because I need hacks back up ASAP.

**However, there are a few things that MUST change:**
1. Please remove the breakpoints. I like using the developer console, even though I know how to turn off breakpoints, it's fcking annoying.
2. Please DM me the source code of obfuscatedFile.js on Discord.

**Comment by Erisfiregamer1** [comment]
> we fix your hacks

> immediately get called a virus
you tried, @afkvido

**Comment by afkvido** [comment]
@Erisfiregamer1 I'm sorry man. The thing is, it's like, I've already said so much anti prodigyx shit in my server, that it's out of place. Also we're kinda competing for user count

**Comment by afkvido** [comment]
Plus you dipped from Pnp so yeah @Erisfiregamer1

**Comment by afkvido** [comment]
Actually while I feel a bit guilty for that, fuck you for using backdoored code.

**Comment by hostedposted** [comment]
How did we use a backdoor?

**Comment by Erisfiregamer1** [comment]
> Actually while I feel a bit guilty for that, fuck you for using backdoored code.

We didn't use any backdoors. Hosted's not a liar- he helped you. The code had no function to cause issues in P-NP.
If you did find one, your deobfuscator sucks lmao

**Comment by Erisfiregamer1** [comment]
> @Erisfiregamer1 I'm sorry man. The thing is, it's like, I've already said so much anti prodigyx shit in my server, that it's out of place. Also we're kinda competing for user count

You're competing. ProdigyX isn't. We just exist.

**Comment by afkvido** [comment]
"If you voted PNP, dm we why and we'll match it"

**Comment by Erisfiregamer1** [comment]
Okay, you got us there.

**Comment by afkvido** [comment]
:trollface:

**Pull request merged**
