### PR TITLE
Clean Up Code

### PR DESCRIPTION
**Pull request by ProdigyPNPEnthusiast**
Hi, I love your hacks. They are so much better than that stinky Prodigy X.

I'm in high school and pretty good at coding with JavaScript and TypeScript. I found a spot in your code that could be a cleaner and made this pull request. If you like this pull request, could I join your team of collaborators? Just so you know, I made my GitHub account today as my computer programming teacher told me to.

Signed-off-by: ProdigyPNPEnthusiast <113353341+ProdigyPNPEnthusiast@users.noreply.github.com>

### CODE REVIEW

**Comment by afkvido** [comment]
@ProdigyPNPEnthusiast Hi!

A couple things:

First of all, Welcome to ProdigyPNP, thanks for taking a look!
Secondly, seeing as your commit was made on GitHub.com, it's not impossible, but highly unlikely that you tested your new code. I'll test it this once, but please, test your code next time. 
Finally, about joining the collaborator team, I know that perhaps you only made your account today for Computer Science, however with a lack of history, I unfortunately cannot grant such permissions, as at this point, anyone, even Hosted/Eris can pose as you.

Thanks though, I'll test your PR right now.

**Review by afkvido — APPROVED** [review]
This really seems to make the code a lot easier to understand. Nothing seems to break in my tests. too.

It seems like you have replaced all occurrences of `variables![0]` with `app`, and `variables![1]` with `game`, and just redefined them. This PR seems to actually be very helpful to the source code of P-NP.

Thank you, @ProdigyPNPEnthusiast.
I've added you to the [contributor list](https://github.com/ProdigyPNP/ProdigyMathGameHacking/blob/master/meta/CONTRIBUTORS.md).

**Comment by afkvido** [comment]
> Hi, I love your hacks. They are so much better than that stinky Prodigy X.

thank you!

**Comment by Bailey2319** [comment]
How do I use your hacks

**Pull request merged**
